### ISSUE TITLE
I can not Login 

### ISSUE THREAD

**Issue by trilias** [ABaumher/galaxy-integration-steam#15]
Ever since I changed my Steam account to a 128 character password Example : 
!zgK6iuyghW*B9veXTTpHw3bj3!E$uGgXCUzmpftC6$s7PspN#sRR9W%oxFgdpC&c^&P!Eiyf!g$PyVkz$9DJERNcKvtni^SFZeeNY8h#%$KZ4zR8WDDPai2ppKX@VYK

I not longer can login on your and the Default steam plugin i get only this.

![GalaxyClient_2023-06-03_11-42-27](https://github.com/ABaumher/galaxy-integration-steam/assets/34447044/045b90c6-27c6-4a11-877d-54df24237049)
Here my log file.
And i Edit the Log to remove my Steam Username from it in the line: steam_network.websocket_client - INFO - Retrieving RSA Public Key for username

[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/ABaumher/galaxy-integration-steam/files/11642298/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by ABaumher** [comment]
> And i Edit the Log to remove my Steam Username from it in the line: steam_network.websocket_client - INFO - Retrieving RSA Public Key for username

yeah, i need to remove that from the logger. It's a relic from when we had to get your username and password separately, so we had to worry about if you went back and changed the username after a failed login. 

We don't log any password information for obvious reasons. The log shows you failing to log in with the user and password, but nothing beyond that. Unfortunately, Steam only really gives us a Pass/Fail, we can't check the username, for example. 

Can you still log in to Steam?
The only thing i can think of is this is causing an error in how we encode your password. Either you have a character that isn't an ASCII character (which is allowed, but maybe our byte conversion breaks it), or we're using utf-8 encoding and steam uses something else. i'm not sure. I'll take a look and see what i can find.

**Comment by trilias** [comment]
Hello Yeah i can still login i try by hand login on Windows Client over web browser and on Android client all works fine

**Comment by trilias** [comment]
oki try steamcmd login that fail he say my password its wrong i think he can not handle the symbols in my password

**Comment by ABaumher** [comment]
> oki try steamcmd login that fail he say my password its wrong i think he can not handle the symbols in my password

That changes what i was about to comment. I think this is a password parsing issue
 ![https://imgs.xkcd.com/comics/account_problems.png](https://imgs.xkcd.com/comics/account_problems.png)
 
 It might be something with how we get the password from html or encode it before we encrpy and send it to Steam. I may be able to test some fixes, but i need some known failing passwords

**Comment by ABaumher** [comment]
Can you give me a few passwords you have tried before but do not work? If that means you need to generate a new password, for yourself, i apologize, but it's the only way i can really test it out. I don't need your username, i'm not trying to log you in, i'm trying to make sure the password matches whenever we need to convert it.

**Comment by trilias** [comment]
oki now i know whats going on symbols are not the problem the password its to long for the plugin and steamcmd if i use a 64 letter long one the login works fine

**Comment by trilias** [comment]
i test now not the exact limit who the plugin and steamcmd start to fail but i can say 128 letters long password not work 64 letters yes works

**Comment by trilias** [comment]
i try also a 128 long password without symbols only big letter small letter and number login fail

**Comment by ABaumher** [comment]
huh. i wonder if our RSA key is not long enough. Steam provides us that so that's weird.

**Comment by trilias** [comment]
my new 64 long password looks like this @WaHcWq$h4Y%Khx##SBpHcpk3rd8zw^b^jhNMkvTiL&AE%P5dcSEPmN@S3AuYQPt
and it works fine you plugin connect to steam and read my games out also steamcmd login

**Comment by ABaumher** [comment]
i might be able to fix it so it works with 128 character (or maybe even 256, idk) passwords. give me a few minutes.

**Comment by trilias** [comment]
the strange its that password problem come only on SteamCMD and the GoG galaxy plugin if you login over the website or the windows or Android client its works fine

**Comment by trilias** [comment]
for me that its done i change now 7 times my password it its pain in the ass to do all the steam guard stuff again and again and fix my phone app again so i stand on 64 letter long then i need many times steamcmd but i can not login with 128 soo i am done lol

**Comment by trilias** [comment]
![2023-06-04_00-14-27](https://github.com/ABaumher/galaxy-integration-steam/assets/34447044/75b4dfa0-288a-414f-a2ee-a5ec5776bbff)
![GalaxyClient_2023-06-04_00-15-27](https://github.com/ABaumher/galaxy-integration-steam/assets/34447044/39e84b9d-3c7c-4708-b6d0-5939a3384f88)

**Comment by ABaumher** [comment]
From what i can tell, steam's password character limit is 64 characters. When you login through the app or website, it just truncates it. We don't truncate it because we don't know to do that. I can't prove it because it's encrypted, and the key changes each time for security reasons.

**Comment by ABaumher** [comment]
I think you were experiencing a quirk in how Steam does passwords. Steam support says the limit is 64 characters, which means their behavior beyond that is undocumented. I'm closing this for now because it's not something we can address. Maybe i could add in a comment if the password is too long saying Steam does funny things beyond 64 characters, but idk

**Comment by nakkamarra** [comment]
I'm experience a similar issue, in theory then if Steam is simply trimming the password at their max character value, I should be able to trim my password input to a length of 64 and successfully log into Steam? I can report on that

**Comment by nakkamarra** [comment]
It appears that I can log in on steam services if I trim my password to be 64 characters, so in theory this plugin could cut the input at 64. Otherwise, it's info that we can just document and have users work around.

**Comment by ABaumher** [comment]
Can you try the first 64 characters in the gog plugin as well? I just want to make sure there's not something else we're missing

**Comment by nakkamarra** [comment]
Yep, with this fork installed and using just the first 64 characters I am able to authenticate properly.

**Comment by ABaumher** [comment]
Okay, I'll patch that in now, actually. If you're willing to test a little more (it'd require changing your password), the example i found from the old code uses the character '§'. If you add that to the first 64 characters of your password and try logging in to steam, can you still log in when you exclude that character? I wish there was a list somewhere of illegal characters but I'll just blindly copy what the old code had i guess, lol


________________________________

**Comment by ABaumher** [comment]
fixed by 6e3591cc2feef3fecb7f80671139074819e056a7
