### ISSUE TITLE
Ubisoft integration? 

### ISSUE THREAD

**Issue by Barleyman** [ABaumher/galaxy-integration-steam#23]
I know this is *Steam* integration project, but in chance Gog is actually going to start using your version, the Ubisoft plugin has a long standing showstopper problem too.

Basically it's one line fix to change the Ubisoft id key, the problem and the fix has been known for quite a while in the GOG forum but of course CDPR has not made that fix on the plugin. 

So if you could fork it, correct the ID and get CDPR to use the fixed version, that'd be double plus good.

**Comment by engiefox** [comment]
GOG Nebula has made a working uplay plugin here: https://github.com/GOG-Nebula/galaxy-integration-uplay/releases/tag/early_release_0.55.5.1

ATM Friends of Galaxy (the group responsible for "stock" plugins) is inactive. Nebula is in talks to replace them, but that will probably take awhile.

**Comment by engiefox** [comment]
Something to keep in mind when asking GOG to use another source for plugins is security issues. The main point of contention is making sure a bad actor doesn't put something malicious in the plugins you can get straight through the GOG plugin browser. So for the time being you'll have to download fixed plugins from groups like Nebula.

**Comment by Barleyman** [comment]
They tell you absolutely nothing, except they added "win", so who knows if it actually works or not. Ubi apparently has changed the ID more than once as well.

**Comment by engiefox** [comment]
I use it, so it does work.

**Comment by engiefox** [comment]
Really discussion about the uplay plugin should be on the respective discussion board (ie https://github.com/FriendsOfGalaxy/galaxy-integration-uplay/issues/42 ) People working on the Steam plugin are a little busy and posting here about something unrelated isn't likely to produce results. (If they wanted to fix the uplay plugin, they'd be doing it already) Though I've heard some of the devs might work on it once the Steam plugin is done.

**Comment by ABaumher** [comment]
I haven't seen a need to fork the Uplay plugin, or else the discussion would go there. Admittedly, this is a bit biased, but all i really care about is getting the plugins *i use* working. I do happen to use the Uplay plugin as well (Ubisoft Connect, as it's technically called), but from what i have seen and tested myself, the fix at Nebula works. If this changes i will look into picking it up. I'm closing this as off-topic, but i am looking to fix some other plugins (namely, PSN and EA Play) after all of this is fixed. But that's going to be a long ways off. 

As @engiefox mentioned, the process of taking over for FoG is not as simple as it seems. We can write our fixes, but they need to undergo security reviews by the people at GOG before they allow them as a native part of their application. Galaxy Nebula is attempting to take over for FoG by doing internal security reviews, setting up config repos so GalaxyClient can auto-update our verified plugins, etc. In the meantime, you will need to get them from either the plugin maintainers (referred to as "Upstream Sources") or from Nebula. If i'm being completely honest, i'm 95% positive FoG *worked* for GOG, but no longer does so. They were the security review team for community plugins (as well as actively developing the Steam one, which is a bit of a conflict of interest and also probably did not sit well with Valve). This obviously complicates things.

**Comment by Barleyman** [comment]
OK, I brought this up since someone mentioned this may be incorporated on galaxy install. I was not aware of FoG and as I said, they tell you essentially nothing about what they did. "win"?

**Comment by engiefox** [comment]
they're referring to inserting "win" into the plugin folders name, why I don't know.
