### ISSUE TITLE
Installed games not showing as installed

### ISSUE THREAD

**Issue by corsa** [ABaumher/galaxy-integration-steam#45]
Using version 1.0.7 on macOS Ventura:

My Steam library syncs and shows up correctly in GOG Galaxy, but installed Steam games do not appear under Installed games. 

I have one game that was installed before I installed this plugin that doesn't show as installed, and I have four games that I successfully used the "Install" button in GOG Galaxy to install, and those don't show up as Installed either.

Log file attached.
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/ABaumher/galaxy-integration-steam/files/12016775/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by ABaumher** [comment]
I'm not on Mac but one of our Nebula devs is. They created a patch for our current refactor (the stable one, not the full rework) that might help you. Iirc they were dealing with the same nonsense. Unfortunately i don't have a MacOS release for 1.20 Alpha, but you could build it yourself.

Looping in @urwrstkn8mare to see if he can get you up to speed for a MacOS version.

**Comment by urwrstkn8mare** [comment]
yep i had the same thing. steam no longer stores app states in the file the plugin is trying to read so it just doesn't show properly. here is a quick zip i just made for 1.2-alpha. 
[steam_v1.2.0.zip](https://github.com/ABaumher/galaxy-integration-steam/files/12029091/steam_v1.2.0.zip)

**Comment by corsa** [comment]
That did the trick, thanks!

**Comment by ABaumher** [comment]
I'll get it added to the 1.2.0 release and tarball in the command. 

Good to know that trick works.
