### ISSUE TITLE
Steam Guard not showing up

### ISSUE THREAD

**Issue by Fevix** [ABaumher/galaxy-integration-steam#46]
**Before start**
- Issue is not known

**Describe the bug**
Attempting to Connect my steam does not show the Steam Guard entry page after entering my username and password

**Expected behavior**
Steam Guard page shows up, allowing me to complete login

**Attached logs**
[logs.zip](https://github.com/ABaumher/galaxy-integration-steam/files/12139124/logs.zip)

**Comment by ABaumher** [comment]
I'm missing some of your log data, there's likely a `steam_<gibberish>.0` file with additional log info in your file.

That said, this seems to be a network issue - the logs show us repeatedly trying to connect to a steam server and failing. It does this for every available server we can connect to, waits a few minutes, then starts over. In the rework, i've actually accounted for this, it'll loop through all available servers, wait, and retry, but it will stop after 5 attempts and give GOG an error that will display something in the UI (Something like 'Connection Cost. Retry')

**Comment by ABaumher** [comment]
In the meantime, you could try it again to see if that was an isolated incident. If not, try using a different network, though you had to have network access to get that far (otherwise we wouldn't know what servers to connect to). 

One final thought, if you have your firewalls configured a little overzealously, it's possible it's blocking us from making a connection to steam. I'd have to check which port we use, but it's a standard one afaik.

**Comment by Fevix** [comment]
I'm connected to Steam just fine, through the Steam client, my browser, and my phone, the first two on the same machine I'm trying to set up GOG on. 

I'm at work at the moment however.

**Comment by Fevix** [comment]
Perhaps of interest is the fact that Vortex (the Nexus mods mod manager) is doing the same exact thing. I can connect to the website just fine, upload and download mods, make comments, do everything. But when Vortex attempts to connect, it fails, and in the logs it shows that it's unable to connect to the website

**Comment by Fevix** [comment]
Turns out SOMETHING with my Internet settings was stopping some programs
from reaching the internet entirely. I Reset my Internet settings and
everything is working fine now. I still don't know what the issue was.

**Comment by ABaumher** [comment]
Going to close this then, feel free to reopen it if the issue comes back. If i had to guess i'd blame a port being closed that we used but i can't be sure.
