### ISSUE TITLE
Plugin crashes because 'CoreServices' module not found

### ISSUE THREAD

**Issue by bgebhardt** [ABaumher/galaxy-integration-steam#7]
**Describe the bug**
I installed v1.0.4 and when I run the plugin it immediately crashes ("Plugin has crashed. Retry.").  The error I get in the logs is:
"ModuleNotFoundError: No module named 'CoreServices'" (see more detailed excerpt below)

I tried to install the package with `pip3 install pyobjc-core`

My guess is though that the packages are bundled with the plugin. But I don't really know how python works.

MacOS version 13.3.1 (a) 
GOG Galaxy Version 2.0.64 (32)

I hope my issue is simple to fix (and hopefully not user error). Happy to help debug it more. And I really appreciate all the work going into fixing the plugin.

**Log excerpt**
I'm getting this error that 'CoreServices' isn't found.

2023-05-22 18:10:48,690 - root - ERROR - Plugin exception
Traceback (most recent call last):
  File "/Applications/GOG Galaxy.app/Contents/Resources/plugin_runner.py", line 35, in <module>
    module = importlib.import_module(filename)
  File "/Applications/GOG Galaxy.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/bryan/Library/Application Support/GOG.com/Galaxy/plugins/installed/steam_ca27391f-2675-49b1-92c0-896d43afa4f8/plugin.py", line 52, in <module>
    from uri_scheme_handler import is_uri_handler_installed
  File "/Users/bryan/Library/Application Support/GOG.com/Galaxy/plugins/installed/steam_ca27391f-2675-49b1-92c0-896d43afa4f8/uri_scheme_handler.py", line 28, in <module>
    from CoreServices.LaunchServices import LSCopyDefaultHandlerForURLScheme
ModuleNotFoundError: No module named 'CoreServices'

**Comment by bgebhardt** [comment]
Ok. I figured out how to set up my development environment and build from source. Now it works!!! (I'll add REALLY nice readme on setting up the plugin and easy to build and install.)

Based on a diff it looks like the CoreServices and maybe pyobjc-framework-CoreServices modules weren't included.

If I diff the 1.0.4 zip and my working directory the following folders/files are missing from 1.0.4 at the root level.

AppKit
Cocoa
CoreFoundation
CoreServices
FSEvents
Foundation
PyObjCTools
__pycache__

objc

psutil
psutil-5.9.5.dist-info

pyobjc_core-9.1.1.dist-info
pyobjc_framework_Cocoa-9.1.1.dist-info
pyobjc_framework_CoreServices-5.1.2.dist-info
pyobjc_framework_FSEvents-9.1.1.dist-info

**Comment by ABaumher** [comment]
You mentioned needing brew to grab python 3.7.9. If we need new install instructions for macs because the Readme install instructions are wrong, if you could either type them up here or fork and do a PR with the updated readme, that'd be great

**Comment by bgebhardt** [comment]
Here's the package attached. No real testing other than to install it and run GOG Galaxy. Will create a PR for updated dev set up instructions later.

[steam_v1.0.4_mac_bgebhardt.zip](https://github.com/ABaumher/galaxy-integration-steam/files/11547130/steam_v1.0.4_mac_bgebhardt.zip)

**Comment by ABaumher** [comment]
I made a minor bugfix, and have another fix i need to address at some point (when i get time to track it down), so i will need you to get me another release at some point. I'll let you know. In the interim, i'm going to add that zip to our releases.

**Comment by ABaumher** [comment]
question: can you install python 3.7.9 from the `python-3.7.9-macosx10.9.pkg` available at https://www.python.org/downloads/release/python-379/ instead of through brew? i'm not sure, but i'd assume python is a verified developer with Apple, whereas building/installing it yourself via `pyenv` might not be. This might let us bypass that digitally signed issue.

**Comment by bgebhardt** [comment]
Sorry. Work is getting in the way. I'll look at this stuff this weekend.

**Comment by bgebhardt** [comment]
@ABaumher I created an updated mac build. Just checked that it would run.

[steam_v1.0.5_mac_beta.zip](https://github.com/ABaumher/galaxy-integration-steam/files/11588812/steam_v1.0.5_mac_beta.zip)

I don't know how to test the unverified developer as I don't get it on my machine. I'll need some help from other mac users to try this out. Or more time to try it on my son's Mac.

**Comment by bgebhardt** [comment]
> question: can you install python 3.7.9 from the `python-3.7.9-macosx10.9.pkg` available at https://www.python.org/downloads/release/python-379/ instead of through brew? i'm not sure, but i'd assume python is a verified developer with Apple, whereas building/installing it yourself via `pyenv` might not be. This might let us bypass that digitally signed issue.

I downloaded the package and tried building with it, but the *.so's are still not signed. I checked running `codesign-dv _multidict.cpython-37m-darwin.so` As they come from installed pip packages I think they should be signed in those. Not sure though. Still learning this stuff.

**Comment by ABaumher** [comment]
I think the unverified won't appear on your machine because you are the developer that compiled it. If macos flagged developers for their own code no one would ever develop in mac. It's when you release it for others that there's an issue. At least, i think that's what Apple does, i have no idea.

**Comment by bgebhardt** [comment]
The *.so's are signed in the Python 3.7 installation. I think maybe I accepted the steam plugin code a long time ago which is why I didn't see the errors on my machine. I'll have to try it on one of my other Macs when I get a few minutes. In the interim we can update the readme installation section with the warning messages.
