### ISSUE TITLE
Origin EA Plugin can't log in

### ISSUE THREAD

**Issue by bakanisan** [ABaumher/galaxy-integration-steam#71]
**Describe the bug**
Origin EA Plugin can't log in, even with correct password

**Attached logs**
[plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log](https://github.com/user-attachments/files/17351718/plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log)

**Comment by yoshimo** [comment]
This is about steam, kind of wrong project here.

**Comment by bakanisan** [comment]
I'm sorry, I wasn't paying attention.
